### ISSUE TITLE
Update Node.js to v16

### ISSUE THREAD

**Issue by munierujp** [npm-update-package/npm-update-package#309]
https://nodejs.org/en/about/releases/

## Targets

- `.nvmrc`
- packages
  - `@types/node`
    - Matches major/minor version to Node.js's version
  - `@tsconfig/node12` -> `@tsconfig/node16`
- `tsconfig.base.json`
  - Replace `@tsconfig/node12` with `@tsconfig/node16`
- `.github/renovate.json`
  - `packageRules`
    - `allowedVersions` for `@types/node`
    - `allowedVersions` for `node`

**Comment by RishiKumarRay** [comment]
where do we have to update?

**Comment by munierujp** [comment]
@RishiKumarRay I've added Targets to description.

**Comment by RishiKumarRay** [comment]
ok let me raise a PR

**Comment by RishiKumarRay** [comment]
@munierujp please review
